---
title: "Blog Post 2"
description: |
  This blog post explores how COVID-19 has spread in South America. Following this initial exploration, a deeper analysis of the region's hardest hittest country, Brazil, observes how the virus has impacted different areas of the nation.
preview: images/brazil-flag-waving-mast.jpg
author:
  - name: Lachlan Moody 27809951
    affiliation: Monash University
    affiliation_url: https://www.monash.edu/
date: 09-16-2020
output:
  distill::distill_article:
    self_contained: false
bibliography: biblio.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(tidycovid19)
library(ggplot2)
library(leaflet)
library(maps)
library(plotly)
library(lubridate)
library(gganimate)
```

## Data Description


## Data Story 1: Spread of COVID19 in South America
```{r regionmap}
tidycovid <- download_merged_data(silent = TRUE, cached = TRUE)

south_america <- tidycovid %>%
  filter(region == "Latin America & Caribbean ") %>%
  group_by(country) %>%
  filter(!is.na(confirmed)) %>%
  summarise(Total_Cases = max(confirmed, na.rm = TRUE),
            population = max(population)) %>%
  mutate(prop = Total_Cases/population*100)

world_map <- map("world", fill = TRUE, plot = FALSE)

cases <- south_america$Total_Cases[match(world_map$names, south_america$country)]

cpal <- colorNumeric("Reds", cases)

leaflet(world_map) %>%
  addProviderTiles("CartoDB.DarkMatter") %>%
  addPolygons(stroke = FALSE,
              smoothFactor = 0.2,
              fillOpacity = 1,color = ~cpal(cases),
              label = paste0(world_map$names, ": ", format(cases, big.mark = ","), " cases")) %>%
  setView(-60, -30, zoom = 2)
```

```{r prop}
prop <- south_america$prop[match(world_map$names, south_america$country)]

cpal2 <- colorNumeric("Reds", prop)

leaflet(world_map) %>%
  addProviderTiles("CartoDB.DarkMatter") %>%
  addPolygons(stroke = FALSE,
              smoothFactor = 0.2,
              fillOpacity = 1,
              color = ~cpal2(prop),
              label = paste0(world_map$names, ": ", round(prop, digits = 2), "% infected")) %>%
  setView(-60, -30, zoom = 2)
```

```{r bar, cache=TRUE}
top10 <- south_america %>%
  arrange(-Total_Cases) %>%
  top_n(8) %>%
  select(country)

bar_data <- tidycovid %>%
  filter(country %in% top10$country)%>%
  mutate(date = format(date), "%Y-%m-%d") %>%
  mutate(country = as.factor(country)) %>%
  mutate(country = fct_rev(country))

  
bar_data %>%
  plot_ly(
    y = ~country,
    x = ~confirmed,
    frame = ~date,
    type = 'bar',
    color = ~country
  ) %>%
  layout(title = "Change in COVID19 cases over time",
         yaxis = list(title = ""),
         xaxis = list(title = "Total Confirmed Cases"),
         showlegend = FALSE) %>%
  animation_opts(frame = 1) %>%
  animation_button(x = 1, 
                   xanchor = "right", 
                   y = 0, 
                   yanchor = "bottom") %>%
  animation_slider(currentvalue = list(prefix = "Date: ", 
                                       font =list(color="red")))


```


## Data Story 2: Spread of COVID19 in Brazil 
```{r brazil, cache=TRUE}
#https://github.com/wcota/covid19br

cases <- read_csv("data/cases-brazil-cities-time.csv")

cities <- read_csv("data/cities_info.csv")

gps <- read_csv("data/gps_cities.csv")


brazil_data <- left_join(cases, gps, by = "ibgeID") %>%
  left_join(cities, by = c("ibgeID" = "ibge")) %>%
  filter(state.x != "TOTAL") %>%
  filter(!is.na(lat))
```

```{r map}
func = colorNumeric(palette = "Dark2", domain = brazil_data$isCountryside)

brazil_data %>%
  filter(date == max(date)) %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(~lon,
                   ~lat,
                   radius = ~totalCases/10000,
                   color = ~func(isCountryside))
```

```{r anim, cache=TRUE}
state <- brazil_data %>%
  group_by(state.x, date) %>%
  summarise(avg = sum(totalCases)) %>%
  ggplot(aes(x = avg, y = reorder(state.x, avg))) +
  geom_col(colour = "light blue", fill = "light blue") +
  transition_time(date) +
  theme_bw() +
  labs(x = "Total Cases", 
       y = "State",
       title = "COVID19 cases in Brazil per state as at: {frame_time}") +
  scale_x_continuous(labels = scales::comma)

state
```


```{r DF}
ovr_date <- brazil_data %>%
  group_by(date) %>%
  summarise(total = sum(totalCases)) %>%
  mutate(source = "Brazil")

SP_date <- brazil_data %>%
  filter(state.x == "SP") %>%
  group_by(date) %>%
  summarise(total = sum(totalCases)) %>%
  mutate(source = "SP")

combined_plot <- combined %>%
  ggplot() +
  geom_line(data = ovr_date, aes(x = date, y = total, colour = "#1b9e77")) +
  geom_line(data = SP_date, aes(x = date, y = total, colour = "#d95f02")) +
  geom_text(aes(x = max(date) + 25, y = max(total)), label = "Overall cases", colour = "#d95f02") +
  geom_text(aes(x = max(date) + 25, y = 900000), label = "SP cases", colour = "#1b9e77") +
  labs(x = "Date",
       y = "Total cases") +
  theme_bw() +
  theme(legend.position = "none") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(limits = as.Date(c("2020-02-25", "2020-10-30"))) +
  ggtitle("Time series of total cases in Brazil and SP")

ggplotly(combined_plot) %>%
  config(displayModeBar = FALSE)
```

