---
title: "Blog Post 1"
description: |
  This blog post explores the impact of COVID-19 in Argentina. In particular, the various protective health measures introduced by the government will be evaluated based on their ability to effectively reduce people's movements and ultimately stop the spread of the virus.
author:
  - name: Lachlan Moody 
    affiliation: Monash University
    affiliation_url: https://www.monash.edu/
date: 08-27-2020
output:
  distill::distill_article:
    self_contained: false
---

## Data Description
```{r setup, include=FALSE}
#install_github("joachim-gassen/tidycovid19")
library(tidyverse)
library(tidycovid19)
library(zoo)
library(ggplot2)
library(kableExtra)
library(DT)
library(broom)
library(sparkline)
library(devtools)


knitr::opts_chunk$set(echo = FALSE, message = FALSE)
sparkline(0)
```

## Data Story
```{r data, include = FALSE}
arg_data <- download_merged_data(silent = TRUE, cached = TRUE) %>%
  filter(country == "Argentina")
  

arg_data_clean <- arg_data %>%
  mutate(lag_confirmed = lag(confirmed),
         daily_confirmed = confirmed - lag_confirmed,
         lag_deaths = lag(deaths),
         daily_deaths = deaths - lag_deaths,
         lag_recovered = lag(recovered),
         daily_recovered = recovered - lag_recovered,
         active = confirmed-recovered,
         lag_active = lag(active),
         daily_active = active - lag_active,
         proportion_infected = confirmed/population,
         proportion_killed = deaths/population)
```

```{r interactive1}
arg_interactive_data <- arg_data_clean %>%
  mutate(apple_mtr_driving = apple_mtr_driving - 100,
         apple_mtr_walking = apple_mtr_walking - 100,
         proportion_infected = paste(round(100*proportion_infected, digits = 2),"%"),
         proportion_killed = paste(round(100*proportion_killed, digits = 2),"%")) %>%
  filter(date != "2020-08-30")

explore <- arg_interactive_data %>%
  select(Date = date,
         "Daily Confirmed Cases" = daily_confirmed,
         "Total Confirmed Cases" = confirmed,
         "Daily Recoveries" = recovered,
         "Total Recoveries" = daily_recovered,
         "Daily Active Cases" = daily_active,
         "Total Active Cases" = active,
         "Daily Deaths" = daily_deaths,
         "Total Deaths" = deaths,
         "Proportion Infected" = proportion_infected,
         "Proportion Killed" = proportion_killed)

datatable(explore, 
          escape = FALSE,
          filter = 'top',
          caption = htmltools::tags$caption( style = 'caption-side: top; text-align: center; color:black; font-size:200% ;','COVID19 case statistics in Argentina'),
          options = list(columnDefs = list(list(className = 'dt-right', targets = 2:11)),
                         fnDrawCallback = htmlwidgets::JS(
  '
function(){
  HTMLWidgets.staticRender();
}
'
)
       )) %>%
  spk_add_deps() 
```




```{r inteactive2}
spk_test <- data.frame(
  Measure = c("driving","walking", "retail/recreation", "grocery/pharmacy", "parks", "transit/stations", "workplaces", "residential"),
  Trend = c(spk_chr(arg_interactive_data$apple_mtr_driving),
  spk_chr(arg_interactive_data$apple_mtr_walking),
  spk_chr(arg_interactive_data$gcmr_retail_recreation),
  spk_chr(arg_interactive_data$gcmr_grocery_pharmacy),
  spk_chr(arg_interactive_data$gcmr_parks),
  spk_chr(arg_interactive_data$gcmr_transit_stations),
  spk_chr(arg_interactive_data$gcmr_workplaces),
  spk_chr(arg_interactive_data$gcmr_residential)
))

spk_test  <- spk_test %>%
  arrange(Measure)

test2 <- arg_interactive_data %>%
  select(driving = apple_mtr_driving,
         walking = apple_mtr_walking,
         "grocery/pharmacy" = gcmr_grocery_pharmacy,
         parks = gcmr_parks,
         residential = gcmr_residential,
         "retail/recreation" = gcmr_retail_recreation,
         "transit/stations" = gcmr_transit_stations,
         "workplaces" = gcmr_workplaces,
         date) %>%
  pivot_longer(cols = driving:workplaces, names_to = "Measure") %>%
  filter(!is.na(value)) %>%
  group_by(Measure) %>%
  summarise("First Observation" = min(date),
            Observations = n(),
            "Average Change" = formatC(round(mean(value), digits =2), format = 'f', digits =2),
            "Standard Deviation" = formatC(round(sd(value), digits =2), format = 'f', digits =2))


test2 <- test2 %>%
  mutate("Average Change" = paste(`Average Change`,"%"),
         "Standard Deviation" = paste(`Standard Deviation`, "%"))

joint <- left_join(test2, spk_test)

datatable(joint, 
          escape = FALSE,
          filter = 'top',
          caption = htmltools::tags$caption( style = 'caption-side: top; text-align: center; color:black; font-size:200% ;','Effect of COVID 19 on public movement'),
          options = list(paging = FALSE, 
                         columnDefs = list(list(className = 'dt-right', targets = 2:5)),
                         fnDrawCallback = htmlwidgets::JS(
  '
function(){
  HTMLWidgets.staticRender();
}
'
)
       )) %>%
  spk_add_deps() 
```



```{r static}
lm_soc_dist <-  lm(daily_confirmed ~ soc_dist, data = arg_data_clean)
lm_mov_rest <-  lm(daily_confirmed ~ mov_rest, data = arg_data_clean)
lm_pub_health <-  lm(daily_confirmed ~ pub_health, data = arg_data_clean)
lm_gov_soc_econ <-  lm(daily_confirmed ~ gov_soc_econ, data = arg_data_clean)
lm_lockdown <- lm(daily_confirmed ~ lockdown, data = arg_data_clean)

lm_tidy <- bind_rows(tidy(lm_soc_dist),
          tidy(lm_mov_rest),
          tidy(lm_pub_health),
          tidy(lm_gov_soc_econ),
          tidy(lm_lockdown)) %>%
  filter(term != "(Intercept)")


lm_glance <- bind_rows(glance(lm_soc_dist),
          glance(lm_mov_rest),
          glance(lm_pub_health),
          glance(lm_gov_soc_econ),
          glance(lm_lockdown))



lm_table <- bind_cols(lm_tidy, 
          lm_glance) %>%
  select(term, estimate, r.squared, "p value" = p.value...5)


lm_table_final <- lm_table %>%
  mutate(estimate = round(lm_table$estimate, digits = 2),
         r.squared = formatC(round(lm_table$r.squared, digits = 2), format = 'f', digits = 2),
         "p value" = formatC(round(lm_table$`p value`, digits = 2), format = 'f', digits =2)) %>%
  mutate(estimate = cell_spec(estimate, 
                              color = if_else(estimate < 0, "white", "black"), 
                              background = ifelse(estimate < 0, "green", "white")),
         r.squared = cell_spec(r.squared, color = ifelse(r.squared > 0.3, "white", "black"), 
                               background = ifelse(r.squared > 0.3, "green", "white")),
         "p value" = cell_spec(`p value`, color = ifelse(`p value` > 0.05, "black", "white"),
                               background = ifelse(lm_table$`p value` < 0.05, "green", "white"))) %>%
  kable(escape = F,
        caption = "Model comparisons for protective health measures", 
        format.args = list(digits = 2),
        align = "lrrr") %>%
  kable_styling(bootstrap_options = c("bordered","striped", "hover"))

lm_table_final


```

